<?php defined('_JEXEC') or die('Restricted access');

$forum = "forum/1-fox-contact-form.html";
$review = 'http://extensions.joomla.org/extensions/contacts-and-feedback/contact-forms/16171';
$translation_url = "forum/19-languages-and-translations/1265-how-to-write-your-own-translation.html";
$download = "downloads/category/1-fox-contact-form.html";
$documentation = "forum/2-documentation.html";
$backlink = "forum/14-licensing/151-remove-the-backlink-powered-by-fox-contact.html";
?>
